kind: Service
apiVersion: v1
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 80
      nodePort: 30000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 2
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: gcr.io/adrianoseie-lab/web-app:1.0.0
        env:
        - name: ENV
          value: "dev"
        livenessProbe:
          httpGet:
            path: /
            port: http
        ports:
        - name: http
          containerPort: 80