kind: Service
apiVersion: v1
metadata:
  name: web-app-service
  namespace: web-app
spec:
  selector:
    app: web-app
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        imagePullPolicy: Always
        image: gcr.io/adrianoseie-lab/web-app:1.0.2
        env:
        - name: ENV
          value: "dev"
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 5000
        ports:
        - name: http
          containerPort: 5000