name: 'build-container-image'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: 'read'
  id-token: 'write'
  
jobs:
  docker-build:
    name: 'docker-build-push'
    runs-on: ubuntu-latest
    environment: dev
  
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
      
      - name: "gcp-auth"
        uses: aseie/actions-templates/gcp-auth@main
        with:
          token_format: 'access_token'
          access_token_lifetime: 300s
          create_credentials_file: true
          GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          GCP_IDENTITY_PROVIDER_POOL: ${{ secrets.GCP_IDENTITY_PROVIDER_POOL }}
          GCP_IDENTITY_PROVIDER: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          
      - name: set version
        run:  |
          echo "IMAGE_TAG=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json)" >> $GITHUB_ENV
      
      - id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v0.4.0
        with:
          cluster_name: dev-adriano-labs-cluster
          location: europe-west3

      - id: get-pods
        run: kubectl get pods
        
      # - name: "docker-build-push"
      #   uses: aseie/actions-templates/docker@main
      #   env:
      #     IMAGE_NAME: "web-app"
      #     DOCKERFILE_PATH: "."
      #   with:
      #     IMAGE_TAG: ${{ env.IMAGE_TAG }}
      #     IMAGE_NAME: ${{ env.IMAGE_NAME }}
      #     GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      #     DOCKERFILE_PATH: ${{ env.DOCKERFILE_PATH }}
      #     access_token: ${{ steps.gcp-auth.outputs.access_token }}
